/*
** EPITECH PROJECT, 2020
** de
** File description:
** de
*/

#include <sys/stat.h>
#include <sys/types.h>
#include <SFML/Graphics.h>
#include <SFML/Window.h>
#include <SFML/System.h>
#include <SFML/Audio.h>
#include <stdlib.h>
#include <unistd.h>
#include <fcntl.h>
#include <stdio.h>

typedef struct rpg_t {
    sfVideoMode video_mode;
    sfRenderWindow *window;
    sfEvent event;
    sfMusic *bowser_menu;
    sfMusic *logo_sound;
    sfMusic *police_cars;
    sfMusic *car_move;
    sfMusic *car_stop;
    sfTexture *background;
    sfTexture *cursor;
    sfTexture *car_one;
    sfTexture *car_two;
    sfTexture *car_three;
    sfTexture *car_four;
    sfTexture *car_five;
    sfTexture *man;
    sfTexture *checkbox;
    sfTexture *checkbox_fill;
    sfTexture *logo;
    sfTexture *logo_bis;
    sfTexture *button;
    sfTexture *button_hover;
    sfTexture *settings;
    sfTexture *letter_t;
    sfTexture *options_t;
    sfTexture *leftarr;
    sfTexture *leftarr_stop;
    sfTexture *rightarr;
    sfTexture *rightarr_stop;
    sfTexture *menulay;
    sfTexture *characterselect;
    sfTexture *overlay_choose;
    sfSprite *overlay_choose_s;
    sfSprite *characterselect_s;
    sfSprite *menulay_s;
    sfSprite *options_s;
    sfSprite *letter_s;
    sfSprite *mainsound_sp;
    sfSprite *muted_box;
    sfSprite *main_soundsn;
    sfSprite *res_sp;
    sfSprite *res_sn;
    sfSprite *sfx_sp;
    sfSprite *sfx_sn;
    sfSprite *fullscreen_box;
    sfSprite *music_sp;
    sfSprite *music_sn;
    sfSprite *lettertwo_s;
    sfSprite *letterthree_s;
    sfSprite *settings_s;
    sfSprite *logo_s;
    sfSprite *car_s;
    sfSprite *cursor_s;
    sfSprite *class_he_chose;
    sfSprite *background_s;
    sfSprite *man_s;
    sfSprite *button_s;
    sfSprite *eyes_s;
    sfSprite *overlay_s;
    sfSprite *bigoverlay_s;
    sfSprite *leave_ops_s;
    sfTexture *eyes_t;
    sfTexture *overlay_t;
    sfTexture *bigoverlay_t;
    sfTexture *leave_ops;
    sfTexture *archer;
    sfTexture *mage;
    sfTexture *warrior;
    sfTexture *light_on;
    sfTexture *light_off;
    sfTexture *open_letter;
    sfTexture *goback;
    sfSprite *lights_s;
    sfFont *font;
    sfText *intro_txt;
    sfText *intro_txt2;
    sfText  *muted_t;
    sfText *fullscreen_t;
    sfText *intro_txt3;
    sfText *car_txt;
    sfText *start_txt;
    sfText *save_one;
    sfText *save_two;
    sfText *save_three;
    sfText *username;
    sfText *optionsone;
    sfText *optionstwo;
    sfText *optionsthree;
    sfText *optionsfour;
    sfText *ch_warrior;
    sfText *ch_mage;
    sfText *ch_archer;
    sfText *master_volume;
    sfText *sfx_volume;
    sfText *music_volume;
    sfText *resolution_t;
    sfText *master_tv;
    sfText *sfx_tv;
    sfText *music_tv;
    sfText *resolution_tv;
    sfText *vita_show;
    sfText *strenght_show;
    sfText *intel_show;
    sfText *agil_show;
    sfText *luck_show;
    sfText *vita_txt;
    sfText *strenght_txt;
    sfText *intel_txt;
    sfText *agil_txt;
    sfText *luck_txt;
    sfText *description;
    sfText *are_you_sure;
    sfText *yes_and_no;
    sfVector2i mo;
    sfVector2f ch_class_v;
    sfVector2f cursor_v;
    sfVector2f logo_v;
    sfVector2f inttxt_v;
    sfVector2f map_v;
    sfVector2f button_v;
    sfVector2f text_v;
    sfVector2f txt_saveone;
    sfVector2f txt_savetwo;
    sfVector2f depht_v;
    sfVector2f txt_savethree;
    sfVector2f eyes_v;
    sfVector2f overlay_v;
    sfVector2f letter_v;
    sfVector2f lettertwo_v;
    sfVector2f letterthree_v;
    sfVector2f bigoverlay_v;
    sfVector2f options_v;
    sfVector2f optionstxt_v;
    sfVector2f leave_v;
    sfVector2f menulay_v;
    sfVector2f choice_v;
    sfVector2f delete_save_v;
    sfIntRect cursor_base;
    sfClock *clock_sprite;
    sfClock *intro;
    sfClock *clock_txt;
    sfClock *spook;
    sfClock *character_time;
    int music_time;
    int sprites_change;
    int logo_change;
    int start_police;
    int anim_i;
    int txt_pointer;
    int stop;
    int go_down;
    int go_spook;
    int overlay;
    int overlay_int;
    int see_options;
    int show_menulay;
    int create_char;
    int what_hechose;
    int size;
    int deep_options;
    int overlay_go;
    char *username_c;
    char *check_the_files;
    char *filenone;
    char *filentwo;
    char *filenthree;
    int saveone;
    int savetwo;
    int savethree;
    int new_one;
    int new_two;
    int new_three;
    int muted_value;
    int master_value;
    int music_value;
    int fullscreen_value;
    int resolution_value;
    int sfx_value;
    int height;
    int width;
    int resol_save;
    int resol_fullscreen;
    int save_nb;
    int is_he_sure_int;
}rpg_t;

void htp(void);
void start_hub(sfRenderWindow *window, int nb_save);
int hub(sfRenderWindow *window, int nb_save);
void switch_it(rpg_t *y);
char *ito(int i);
void txt_application(sfText *txt, sfFont *font, sfVector2f scale, char *str);
void resolution_set_strings(struct rpg_t *y);
void the_limits(struct rpg_t *y);
void options_overlay(struct rpg_t *y);
void more_options_overlay(struct rpg_t *y);
void options_pressed(struct rpg_t *y);
int deep_options(struct rpg_t *y);
void arrows(struct rpg_t *y);
void boxes(struct rpg_t *y);
void update(struct rpg_t *y);
void deep_options_set(struct rpg_t *y);
void options_specific_draw(struct rpg_t *y);
void size_one(struct rpg_t *y);
void size_two(struct rpg_t *y);
void size_three(struct rpg_t *y);
void size_four(struct rpg_t *y);
void fullscreen(struct rpg_t *y);
int my_strlen(char *str);
void resize(rpg_t *y);
void escape_key_m(rpg_t *y);
void initialization_m(struct rpg_t *y);
void overlay_bis(struct rpg_t *y);
void animated_strings(char *str, sfText *intro_txt, sfClock *clock_txt, rpg_t *y);
void more_text(rpg_t *y);
void vector_initialization_m(struct rpg_t *y);
void texture_set_m(struct rpg_t *y);
void draw_m(struct rpg_t *y);
void clock_sprites(struct rpg_t *y);
void mouse_cursor(struct rpg_t *y);
int intro(rpg_t *y);
void draw_intro(rpg_t *y);
void vect_intro(rpg_t *y);
void init_intro(rpg_t *y);
void more_init_intro(rpg_t *y);
void overlay(struct rpg_t *y);
void interaction(struct rpg_t *y);
void change_vectors(struct rpg_t *y);
void button_pressed(struct rpg_t *y);
void show_me_the_txt(rpg_t *y);
void character_select(struct rpg_t *y);
void create_window(struct rpg_t *y);